baseURL = 'https://prule.github.io/pauls-blog/'
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'Pauls Blog'
theme = 'simple-beauty'

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.asciidocExt]
    workingFolderCurrent = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = "github"

# Define the number of posts per page
[pagination]
    pagerSize = 10

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "References"
    url = "/page/references"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/page/projects"
    weight = 3
[[menu.main]]
    name = "Book Summaries"
    url = "/page/booksummaries"
    weight = 4

[params]
  description = "Random programming thoughts"
  slogan = "Programming is life"

  # Social links
  linkedin       = "https://www.linkedin.com/in/paulrule/"
  github         = "https://github.com/prule"
  medium         = "https://medium.com/@prule70"
  substack       = "https://paulr70.substack.com"

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"

[services]
  [services.googleAnalytics]
    ID = 'G-QYKTN5W199'
